apiVersion: v1
kind: Service
metadata:
  name: pizza-service
  namespace: rohan-pizza
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: pizza