apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP