apiVersion: v1
kind: Service
metadata:
  name: data-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: data
  ports:
    - protocol: TCP
      port: 8080
      name: http