apiVersion: v1
kind: Pod
metadata:
  name: fruit-service
  labels:
    app: fruit-service
spec:
  containers:
  - name: fruit-ctr
    image: linuxacademycontent/legacy-fruit-service:1
  - name: ambassador
    image: haproxy:1.7
    ports:
    - containerPort: 80
    volumeMounts:
    - name: fruit-service-ambassador-config
      mountPath: /usr/local/etc/haproxy
  volumes:
  - name: fruit-service-ambassador-config
    configMap:
       name: fruit-service-ambassador-config
       items:
        - key: config
          path: haproxy.cfg