apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysqlpod
spec:
  containers:
    - name: mysql-container
      image: mysql:5.6
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-password
              key: mykey
      volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-vol
  volumes:
    - name: mysql-vol
      persistentVolumeClaim:
        claimName: mysql-pv-claim